swagger: '2.0'
info:
  description: Number-to-roman-conversion API reference for developers
  title: Number-to-roman-conversion
host: localhost:8080
basePath: /
tags:
  - name: roman-numeral-conversion-controller
    description: Roman Numeral Conversion Controller
paths:
  /romannumeral:
    get:
      tags:
        - roman-numeral-conversion-controller
      summary: toRomanNumber
      operationId: toRomanNumberUsingGET
      produces:
        - '*/*'
      parameters:
        - name: query
          in: query
          description: query
          required: true
          type: string
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/RomanNumber'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
definitions:
  RomanNumber:
    type: object
    properties:
      input:
        type: integer
        format: int32
      output:
        type: string
    title: RomanNumber
